statictext:
    path:     /
    defaults: { _controller: "AdminUserBundle:StaticText:index" }

statictext_show:
    path:     /{id}/show
    defaults: { _controller: "AdminUserBundle:StaticText:show" }

statictext_new:
    path:     /new
    defaults: { _controller: "AdminUserBundle:StaticText:new" }

statictext_create:
    path:     /create
    defaults: { _controller: "AdminUserBundle:StaticText:create" }
    methods:  POST

statictext_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminUserBundle:StaticText:edit" }

statictext_update:
    path:     /{id}/update
    defaults: { _controller: "AdminUserBundle:StaticText:update" }
    methods:  [POST, PUT]

statictext_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminUserBundle:StaticText:delete" }
    methods:  [POST, DELETE]
