services:
    sonata.admin.mailinguserconfig:
        class: Application\MailingBundle\Admin\MailingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "UserConfig MailingLists" }
        arguments:
            - ~
            - Application\MailingBundle\Entity\UserConfig
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationMailingBundle]]