parameters:
#    application_mailing.example.class: Application\MailingBundle\Example

services:
#    application_mailing.example:
#        class: %application_mailing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
