parameters:
#    admin_parcours.example.class: Admin\ParcoursBundle\Example

services:
#    admin_parcours.example:
#        class: %admin_parcours.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
