services:
    sonata.admin.user:
        class: Admin\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Admin\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AdminUserBundle]]

    admin_user.admin.static_text:
        class: Admin\UserBundle\Admin\StaticTextAdmin
        arguments: [~, Admin\UserBundle\Entity\StaticText, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Content", label: "Texts Statiques"}
