services:
    sonata.admin.user:
        class: Admin\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Admin\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AdminUserBundle]]