application_main_homepage:
    pattern:  /
    defaults: { _controller: ApplicationMainBundle:Default:index }

application_main_help:
    pattern:  /aide
    defaults: { _controller: ApplicationMainBundle:Default:aide }

