admin_mailing_homepage:
    pattern:  /mailing
    defaults: { _controller: "AdminMailingBundle:Default:index" }

admin_mailing_mailinglist_add:
    pattern: /mailing/add
    defaults: { _controller: "AdminMailingBundle:Default:add" }

admin_mailing_mailinglist_edit:
    pattern: /mailing/{id}/edit
    defaults: { _controller: "AdminMailingBundle:Default:edit" }
    requirements:
       id: \d+

aadmin_mailing_mailinglist_delete:
   pattern: /mailing/{id}/delete
   defaults: { _controller: "AdminMailingBundle:Default:delete" }
   requirements:
      id: \d+