application_yearbook_listmessages:
    path:     /yearbook/list
    defaults: { _controller: ApplicationYearbookBundle:Default:list }

application_yearbook_newmessage:
    path:     /yearbook/new/{id}
    defaults: { _controller: ApplicationYearbookBundle:Default:new }
    requirements:
        id: \d*
application_yearbook_updatemessage:
    path: /yearbook/update/{id}
    defaults : {_controller: ApplicationYearbookBundle:Default:update}
    requirements:
        id: \d*

application_yearbook_delete:
    path:  /yearbook/{id}/delete
    defaults: { _controller: ApplicationYearbookBundle:Default:delete }
    requirements:
        id: \d*