services:
    sonata.admin.cotisationtype:
        class: Application\CotisationBundle\Admin\TypeCotisationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Type de Cotisation" }
        arguments:
            - ~
            - Application\CotisationBundle\Entity\TypeCotisation
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationCotisationBundle]]