services:
    sonata.admin.cotisationtype:
        class: Application\CotisationBundle\Admin\TypeCotisationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Types de Cotisations" }
        arguments:
            - ~
            - Application\CotisationBundle\Entity\TypeCotisation
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationCotisationBundle]]
    sonata.admin.cotisation:
        class: Application\CotisationBundle\Admin\CotisationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Cotisations" }
        arguments:
            - ~
            - Application\CotisationBundle\Entity\Cotisation
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationCotisationBundle]]
    sonata.admin.invoice:
        class: Application\CotisationBundle\Admin\InvoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Factures" }
        arguments:
            - ~
            - Application\CotisationBundle\Entity\Invoice
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationCotisationBundle]]