application_cotisation_homepage:
    path:     /cotisation
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:index }

application_cotisation_new:
    path:     /cotisation/new
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:add }
